package by.melnikov.medicinesxml.entity;

public enum MedicineTags { //FIXME
    MEDICINE,
    MEDICINES,
    ANTIBIOTIC, NEED_PRESCRIPTION,
    VITAMINS, FOR, GROUP,
    NAME,
    PACKAGE, QUANTITY, PRICE, SIZE,
    COMPANY,
    ANALOG,
    SHAPE,
    DOSAGE, DOSE, FREQUENCY,
    CERTIFICATE, PERMISSION_DATE, EXPIRED_DATE, REGISTRATION_NUMBER, REGISTRY_ORGANIZATION

}
